version: "3"

services:
  frontend:
    build: ./services/frontend/
    ports:
      - "8000:8000"
    restart: always

  api:
    build: ./services/api
    ports:
      - "8001:8001"
    restart: always

  mongojs:
    build: ./services/mongojs
    ports:
      - "8002:8002"
    env_file:
      - "./services/mongojs/mongojs.env"
    restart: always
