version: "3"

services:
  frontend:
    build: ./services/frontend/
    ports:
      - "8000:8000"
    restart: always
  
  api:
    build: ./services/api
    ports:
      - "8001:8001"
    restart: always