version: "3"

services:
  frontend:
    build: ./services/frontend/
    container_name: "frontend"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.rule=Host(`philippstuerner.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
       
  api:
    build: ./services/api/
    container_name: "api"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.rule=Host(`api.philippstuerner.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=philipp.stuerner@web.de"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 
  
  mongojs:
    build: ./services/mongojs
    container_name: "mongojs"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongojs.tls=true"
      - "traefik.http.routers.mongojs.rule=Host(`mongodb.philippstuerner.com`)"
      - "traefik.http.routers.mongojs.entrypoints=websecure"
      - "traefik.http.routers.mongojs.tls.certresolver=myresolver"
    env_file:
      - "./services/mongojs/mongojs.env"

volumes:
  traefik-public-certificates:

